name: kachaika
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.1+2

environment:
  sdk: ">=3.0.0 <4.0.0" # Убедитесь, что версия SDK соответствует вашей установленной версии Flutter

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  hexcolor: ^3.0.1
  shared_preferences: ^2.3.3
  provider: ^6.1.2
  flutter_svg: ^2.0.16
  auto_route: ^8.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^8.0.0
  build_runner: ^2.4.9
  flutter_launcher_icons: ^0.14.2
  flutter_lints: ^5.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/image/icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/image/icon.png" 

flutter:
  uses-material-design: true

  assets:
    - assets/background/background.png
    - assets/image/Logo.png
    - assets/fonts/SFPROregular.ttf
    - assets/image/pop.png

  fonts:
    - family: SFPROregular
      fonts:
        - asset: assets/fonts/SFPROregular.ttf